export const FETCH_SKILLS_SUCCESS = "FETCH_SKILLS_SUCCESS";

export const FETCH_EVALUATION_CRITERIAS_SUCCESS =
  "FETCH_EVALUATION_CRITERIAS_SUCCESS";
export const FETCH_CRITERIAS_FOR_EVALUATION_SUCCESS =
  "FETCH_CRITERIAS_FOR_EVALUATION_SUCCESS";

export const FETCH_TAGS_SUCCESS = "FETCH_TAGS_SUCCESS";

export const FETCH_EVALUATED_LIST_SUCCESS = "FETCH_EVALUATED_LIST_SUCCESS";

export const FETCH_EMPLOYEE_EVALUATION_RECORD_SUCCESS =
  "FETCH_EMPLOYEE_EVALUATION_RECORD_SUCCESS";

export const FETCH_EMPLOYEES_SUCCESS = "FETCH_EMPLOYEES_SUCCESS";
export const FETCH_USER_SUCCESS = "EXPORT_USER_SUCCESS";

export const FETCH_EMPLOYEES_WITH_CRITERIAS_SUCCESS =
  "FETCH_EMPLOYEES_WITH_CRITERIAS_SUCCESS";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTHENTICATED = "AUTHENTICATED";

export const SIGNOUT = "SIGNOUT";
// export const SIGNOUT_FAIL = "SIGNOUT_FAIL";

export const ADD_EMPLOYEE_TO_TEAM_SUCCESS = "ADD_EMPLOYEE_TO_TEAM_SUCCESS";
export const FETCH_EMPLOYEE_TEAM_SUCCESS = "FETCH_EMPLOYEE_TEAM_SUCCESS";

export const FETCH_EMPLOYEE_SKILLS_SUCCESS = "FETCH_EMPLOYEE_SKILLS_SUCCESS";

// export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const SIGNED_UP = "SIGNED_UP";

// export const SIGNUP_VERIFICATION_SUCCESS = "SIGNUP_VERIFICATION_SUCCESS";
// export const SIGNUP_VERIFICATION_FAILED = "SIGNUP_VERIFICATION_FAILED";

// export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
// export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";

export const LOADING_START = "LOADING_START";
export const ERROR_HANDLER = "ERROR_HANDLER";
export const SET_SPINNER_LOADER = "SET_SPINNER_LOADER";

// export const SEARCH_EMPLOYEE_SUCCESS = "SEARCH_EMPLOYEE_SUCCESS";
